### ISSUE TITLE
sound can not pause or resume on android when blur,focus event happens(switch brower to any other app then switch back)

### ISSUE THREAD

**Issue by yanyuling** [phaserjs/phaser#5168]
## Version

* Phaser Version:3.22.0

* Operating system: MacOS 

* Browser:

## Example Test Code

export default class GameScene extends Phaser.Scene {

    create() {
       let bg = this.add.image(750/2,1334/2,"compose_bg");
       this.sound.add("bgm_10s").play({
           loop: true,
       });
    }

    preload() {
        this.load.image('compose_bg', "assets/textures/compose_bg.jpeg");
        this.load.audio('bgm_10s', "assets/audios/bgm_10s.mp3");
    }
}

const config = {
    type: Phaser.AUTO,
    backgroundColor: '#000000',
    width: 750,
    height: 1334,
    autoFocus: true,
    scene: GameScene,
    parent: 'gamecanvas',
    scaleMode: Phaser.Scale.ScaleModes.FIT,
};
const game = new Phaser.Game(config);

**Comment by sangnv-mirabo** [comment]
any update here? 
i'm facing same problem when sounds play continuously even when had switched to another app

**Comment by photonstorm** [comment]
We've taken the decision to recode the Phaser Audio system from scratch and replace the existing one. This will remove the division between Web Audio and HTML Audio (you'll be able to have both together), along with lots of other required features and API updates. Development work will start in Q2 2024. As a result, we are going to mothball all audio-related issues rather than try to monkey-patch solutions in.
