### ISSUE TITLE
browser close from fullscreen causes black screen after opening it again.

### ISSUE THREAD

**Issue by novaknole** [phaserjs/phaser#5196]
## Version

* Phaser Version: 3.22

* Operating system: Android Xiaomi

* Browser: Chrome

## Description

@samme 

I start the game in fullscreen mode by using `this.game.scale.startFullscreen()`.  All looks good. Then I click phone's middle button on the screen which closes the browser. After I open the browser, game still continues playing, but the whole screen goes black. 

Any ideas ?

**Comment by photonstorm** [comment]
Due to the age of this issue and the legacy hardware / Phaser version involved, we're going to close it off, even though it wasn't officially addressed as resolved. If you can replicate this issue on modern hardware (and Phaser v3.70), then feel free to open a brand new issue with a code sample, and we'll look into it.
