### ISSUE TITLE
HTML-AUDIO iOS sound delayed 

### ISSUE THREAD

**Issue by jamessimo** [phaserjs/phaser#5556]
## Version
* Phaser: 3.51 & 3.52

* Operating system: iOS 14.4

* Browser: Safari iOS + Chrome iOS

## Description
When using any sounds in HTML5 audio there are a few hundred milliseconds delay. Saw on the phaser discourse that one person said they mitigated this using .m4a files with the same bit rate. This didn’t work for me however I did have some sounds I was unable to make m4a. 

## Example Test Code

```
var config = {
  ...
    audio: {
        disableWebAudio: true
    }
    
    
    this.load.audio('sfx', [
        'assets/audio/SoundEffects/magical_horror_audiosprite.ogg',
        'assets/audio/SoundEffects/magical_horror_audiosprite.mp3'
    ]);
    
     fx = this.sound.add('sfx');

...

```

## How to reproduce 

Please see the example at https://phaser.io/examples/v3/view/audio/html5-audio/markers-pause-resume#

On your PC you can click any of the play sound buttons as fast as you can and you will always hear something 

on iOS there is a few hundred-millisecond delay, if you tap fast on the buttons you will not hear the sound as the delay keeps getting restarted. 

This issue happens regardless if you use a sound marker or not. 

Tested using .m4a and .a3c both have the same issue.

**Comment by samme** [comment]
I think HTML5 audio is high-latency by nature, especially on iOS.

**Comment by SlimHajRomdhane** [comment]
The delay you are experiencing with HTML5 audio on iOS devices is a known issue and is related to how iOS handles the playback of HTML5 audio. This is not specific to Phaser, but rather a limitation of the underlying web technology on iOS.

One possible workaround for this issue is to use Web Audio instead of HTML5 audio. You can enable Web Audio in Phaser by removing the disableWebAudio property from your game's audio configuration:

var config = {
    ...
    audio: {
        // disableWebAudio: true // remove this line
    }
};

By default, Phaser will use Web Audio if it is available, and will fall back to HTML5 audio if it is not. However, if you explicitly disable Web Audio, Phaser will only use HTML5 audio, which may cause the delay on iOS devices.

Another possible workaround is to preload the audio files and then play them immediately when needed, instead of trying to play them in rapid succession. This can help reduce the delay between playback, as the audio file will already be loaded into memory and ready to play.

this.load.audio('sfx', [
    'assets/audio/SoundEffects/magical_horror_audiosprite.ogg',
    'assets/audio/SoundEffects/magical_horror_audiosprite.mp3'
]);

this.sound.add('sfx');

You can then play the sound whenever you need it, without needing to wait for it to load:

this.sound.play('sfx');


Note that this workaround may not completely eliminate the delay on iOS devices, but it can help reduce it in some cases.
Hope this helps!
-SlimHR

**Comment by photonstorm** [comment]
We've taken the decision to recode the Phaser Audio system from scratch and replace the existing one. This will remove the division between Web Audio and HTML Audio (you'll be able to have both together), along with lots of other required features and API updates. Development work will start in Q2 2024. As a result, we are going to mothball all audio-related issues rather than try to monkey-patch solutions in.
