### ISSUE TITLE
Audio sprite doesn't play all the sounds

### ISSUE THREAD

**Issue by trynx** [phaserjs/phaser#5812]
## Version

* Phaser Version: 3.54.0

* Operating system: window 10

## Description

Hello :)

I have an audio sprite with which is 2 minutes  long and separated to various tracks, for some reason the tracks of around 110-115 seconds doesn't play at all, but when playing the original sound file, I do hear it there.

Phaser doesn't throw any error or anything, I did the same code to play other sounds and in the same audio sprite and they work perfectly...

I did try various browsers (Opera, FireFox & Edge), all had the same issue.

## Example Test Code

scene.sound.playAudioSprite("GAME_AUDIO", "Shoot");

![f9496450703d5cd6a2f977460ba607ce](https://user-images.githubusercontent.com/25723003/130422342-a55f090b-7470-4c95-b93f-e0cc4ea7f278.png)

**Comment by photonstorm** [comment]
I need the audio file and audio sprite json in order to test this.

**Comment by trynx** [comment]
[game_sounds.zip](https://github.com/photonstorm/phaser/files/7208418/game_sounds.zip)

**Comment by photonstorm** [comment]
We've taken the decision to recode the Phaser Audio system from scratch and replace the existing one. This will remove the division between Web Audio and HTML Audio (you'll be able to have both together), along with lots of other required features and API updates. Development work will start in Q2 2024. As a result, we are going to mothball all audio-related issues rather than try to monkey-patch solutions in.

Also, worth adding that HTML5 Audio is so high latency that really short audio sprites will often be skipped / never played.
