### ISSUE TITLE
Objects with post fx pipeline don't render correctly to render texture

### ISSUE THREAD

**Issue by vforsh** [phaserjs/phaser#5942]
## Version
Phaser 3.60 beta 4 (built from the repo)

## Description
Objects with post fx pipeline don't render correctly to render texture. Y position is shifted down and they are squeezed vertically.

![2021-12-09_18-12-14](https://user-images.githubusercontent.com/190223/145422776-64a77cd1-5276-4990-98be-9e727960d21c.png)

## Example Test Code
Demo - https://codesandbox.io/s/render-texture-glow-post-fx-pruru?file=/src/index.ts

```
this.renderer.pipelines.addPostPipeline("GlowPostFX", GlowPostFX)

let rect = this.add.image(20, 20, "__WHITE")
rect.setOrigin(0)
rect.setDisplaySize(200, 60)
rect.setTintFill(0xfff000)

let text = this.add.text(20, 100, "glow", { fontSize: "70px" })

// comment these lines to turn off the glow
rect.setPostPipeline("GlowPostFX")
text.setPostPipeline("GlowPostFX")

let rt = this.add.renderTexture(0, 300, 500, 200)
rt.fill(0xff0000, 0.5)
rt.draw(rect)
rt.draw(text)
```

**Comment by photonstorm** [comment]
Sorry, but I cannot think of a way to allow this to be supported. PostFX pipelines are applied to an entirely separate frame buffer, after the Sprite (or whatever) has been rendered, and then copied back to the 'screen' again. I can't apply the Post FX to the Render Texture, or it would apply that fx to everything already drawn on it (not just the Sprite), and equally I can't copy the fx frame to the Render Texture frame because it'll almost certainly not be in the correct position for the actual sprite, as there's no real way to tell where the sprite was drawn to it.
