### ISSUE TITLE
Pointer events fired on window.top

### ISSUE THREAD

**Issue by rvh1986** [phaserjs/phaser#6019]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10

* Browser:  Chrome 98.0.4758.102

## Description

Pointer events are fired when clicking in the top window of the page the iframe is embedded on, meanwhile ignore the margin the game is placed from the top or left of the window.

This only happens when the iframe is on the same domain as the page that embeds it.

I'm not sure if this is known behaviour, it seems a bit odd. It can be solved by turning window events off in the GameConfig, but this is not wanted for some games.

## Example Test Code

Here's an example of what's happening, the embedded game has a fullscreen and settings button on the right top that can be activated by clicking in the red square just above the iframe.

[https://www.joypadmedia.com/pointer-test/](https://www.joypadmedia.com/pointer-test/)

**Comment by photonstorm** [comment]
Listening to `window.top` (when available, not all sites allow this) is done on purpose:

* If `inputWindowEvents` is set in the Game Config, then the `MouseManager` will now listen for the events on `window.top` instead of just `window`, which should help in situations where the pointer is released outside of an embedded iframe. This check is wrapped in a `try/catch` block, as not all sites allow access to `window.top` (specifically in cross-origin iframe situations) Fix #4824 (thanks @rexrainbow)
* `MouseManager.isTop` is a new boolean read-only property that flags if the mouse event listeners were attached to `window.top` (true), or just `window` (false). By default Phaser will attempt `window.top`, but this isn't possible in all environments, such as cross-origin iframes, so it will fall back to `window` in those cases and set this property to false (thanks BunBunBun)

I'm happy for this to be the default setting, as it's the most common use-case, and you can turn it off if it doesn't work for your site.
