### ISSUE TITLE
Cannot transition to scene with same key

### ISSUE THREAD

**Issue by likwidgames** [phaserjs/phaser#6045]
## Version

* Phaser Version:
3.55.2

* Operating system:
Mac OSX

## Description

We have a scene, "overworld", which is used for all overworld levels in our game. Rather than creating a new scene for 50+ levels, we simply load this scene and pass data to it to build the level. Using `this.scene.start('overworld', data)` works perfectly to load the same scene with new data. However, using `
this.scene.transition({
                    target: 'overworld',
                    data: {
                        id: 3
                    },
                });
`
 and using 'overworld' as the target, does not do anything. I have confirmed the issue is due to us using the same key as the scene that is currently loaded.

## Example Test Code

Working
`this.scene.start('overworld', data)`

Not working
`
this.scene.transition({
                    target: 'overworld',
                    data: {
                        id: 3
                    },
                });
`

**Comment by samme** [comment]
I think that's as designed, because a scene can't transition to itself.

**Comment by likwidgames** [comment]
> I think that's as designed, because a scene can't transition to itself.

I assume so as well. However, to accomplish a transition, I'd be forced to create a different scene for 50+ levels in my game, which isn't very efficient.

**Comment by rexrainbow** [comment]
Might have 2 scenes, ping-pong between these 2 scenes..

**Comment by vforsh** [comment]
Or you can use `scene.restart` and pass level number as a data

**Comment by likwidgames** [comment]
> Or you can use `scene.restart` and pass level number as a data


This does not allow you to use transition options and events.

**Comment by likwidgames** [comment]
> Might have 2 scenes, ping-pong between these 2 scenes..

Ya, this may be the way to go unfortunately.

**Comment by photonstorm** [comment]
It works this way by design. You cannot transition to the same Scene, because it would require 2 instances of the same Scene to exist and be running in order to be able to do this. However, you likely don't need a Scene transition if you're just going from the same Scene to itself again - rather just do whatever visual effect you need (camera fade, etc) then restart the Scene, pass in some scene data and do a transition-in effect (camera fade up, flash).

I have, however, updated the docs to make it clear you cannot transition to the same Scene.

**Comment by samme** [comment]
https://codepen.io/samme/pen/qBdpeVP
