### ISSUE TITLE
loading htmlTexture in WebGL (Chrome and MS Edge)

### ISSUE THREAD

**Issue by raggedgenes** [phaserjs/phaser#6069]
## Version

* Phaser Version: 3.55.2

* Operating system: Win 10

* Browser: Chrome, MS Edge

## Description

When trying to load a html texture there is this error msg when WebGL is used as renderer :
"Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded."

This only occurs in Chrome and MS Edge. Firefox is okay. 
The **modified** example code produces the this error as well.
(http://labs.phaser.io/edit.html?src=src/loader/html/load%20html%20to%20texture.js&v=3.55.2)

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#efefef',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

var image;

function preload ()
{
    this.load.htmlTexture('test1', 'assets/html/test1.html', 512, 512);
}

function create ()
{
    image = this.add.image(400, 300, 'test1').setOrigin(0);
}

function update ()
{
    image.rotation += 0.01;
}
```

**Comment by photonstorm** [comment]
If the HTML contains external data, i.e. an image, or indeed anything that breaks CORs, then this error will be fired by the _browser_ because it's breaking browser cross-origin policies. The only way to fix this is to ensure the HTML is fully self-contained, or that your server is correctly set up to allow full CORs access from all hosts you need.
