### ISSUE TITLE
Silent wrong behaviour when depth is not a number

### ISSUE THREAD

**Issue by monteiz** [phaserjs/phaser#6092]
## Version

* Phaser Version: 3.55.2

* Operating system: macOS

* Browser:

## Description

When assigning a non-number value to a GameObject `depth` property, the object silently disappear or starts to flash intermittently. No error or warning is given. From my observation, both [Image](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Image.html) and [BitmapText](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.BitmapText.html) suffers from this problem.

Instead, the code execution should be stopped and an error should be raised. Or at least a warning, to preserve backward compatibility.

## Example Test Code

https://codepen.io/monteiz/pen/popMZqr

**Comment by photonstorm** [comment]
I've updated the JSDocs to make it explicitly clear you should only ever set the `depth` to a number.

However, I'm not going to enforce this at runtime by parsing the input value, because I'm not willing to pay the overhead of doing this, especially for a property that is frequently set at very high interval rates.

The onus is on you to ensure your data-types are correct (i.e. use TypeScript or similar).
