### ISSUE TITLE
this.load.image(key,path) repeat 、 Why is the key path not covered by the new one

### ISSUE THREAD

**Issue by BrickerZou** [phaserjs/phaser#6119]
## Version

* Phaser Version:3.5

* Operating system:windows

* Browser:chrome

## Description

When I enter sceneB, the back displayed is the back of sceneA,
Why is the 'back' key not covered by the new one?
How do I cover the key  'back' of sceneA in sceneB?

## Example Test Code

```
//sceneA.js
 this.load..image('back', 'back1.png')
...
this.scene.start('sceneB')

//sceneB.js
 this.load..image('back', 'back2.png')
//
```

## Additional Information

///

**Comment by photonstorm** [comment]
Because the 2nd time you load it, the Loader will see you've already got a texture in the Texture Manager called `back` and skip loading it again. You cannot replace a texture by simply loading it, you need to delete it from the Texture Manager first and only then can you reload it. But any Sprites using it will also need to have it removed until the new version has loaded as well.
