### ISSUE TITLE
Sound stops when clicking outside the iframe

### ISSUE THREAD

**Issue by robinheidrich** [phaserjs/phaser#6168]
## Version

* Phaser Version: v3.60.0-beta.9

* Operating system: Windows 11

* Browser: Google Chrome 103.0.5060.114

## Description

I have my game in an `<iframe>` to embed it on the website.

When I click outside the iframe, the sound pauses but the game continues to run (because the focus is not lost).

This should also apply to the sound, that it only pauses when I change tabs. Otherwise the sound would be out of sync with the game.

## Additional Information

I think the `HIDDEN` event should be used instead of `BLUR` in BaseSoundManager ([line 151](https://github.com/photonstorm/phaser/blob/master/src/sound/BaseSoundManager.js#L151)).

**Comment by robinheidrich** [comment]
I did some testing and came to the conclusion that it would be best to:

replace `Phaser.Core.Events.BLUR` with `Phaser.Core.Events.HIDDEN`, and
replace `Phaser.Core.Events.FOCUS` with `Phaser.Core.Events.VISIBLE`.

This way the sound would only pause when the game is not visible. Possibly `pauseOnBlur` would then have to be renamed. 😛

**Comment by photonstorm** [comment]
Why not just set `pauseOnBlur` to false? It will prevent sound from being paused when the game loses focus, which is exactly what's happening.

**Comment by robinheidrich** [comment]
`pauseOnBlur` would let the audio continue playing even if the game is not visible. Then the audio would be out of sync with the game.

I want the audio to stop just like the game when it is no longer visible.

**Comment by photonstorm** [comment]
I would want the audio to stop playing if I swap to another application (outside of the browser, so not another tab). It's still visible in this state, so using 'hidden' wouldn't trigger it, but it's not focused because you're not playing it, so it shouldn't make any noise.

If you want to trigger it on 'hidden' for your specific use case then you can add a dom event listener yourself and set it to invoke `this.sound.onBlur()` and `onFocus()`.

**Comment by robinheidrich** [comment]
But the game also pauses when you switch tabs, so it would only make sense if the audio pauses as well? Or does it work differently on mobile devices?

**Comment by photonstorm** [comment]
Request Animation Frame is throttled (and eventually stopped) by the browser if you switch tabs, yes. So your game effectively pauses, regardless if you want it to or not (and you cannot prevent this). So by default, we pause the audio to match this behavior.

The same thing happens if you open another application (on a desktop) and cover your game with it. For example, open Notepad, drag it over Chrome so the canvas isn't visible and Chrome will eventually halt Request Animation Frame, pausing your game. So we disable audio too, because focus has been lost. In this case 'hidden' won't fire because it's still in the browser viewport. The new Observable APIs may allow for more fine-grained control over this.

I understand your request because in _your_ situation it's unwanted behavior, but you can achieve the desired result by creating 2 of your own event listeners and hooking them to the Sound Manager.

**Comment by robinheidrich** [comment]
~~I see, wouldn't it be possible for Phaser to check if requestAnimationFrame is stopped, and if so, pause the audio?~~

I don't need the sound stopped anymore.

**Comment by photonstorm** [comment]
Sadly, there is no event we can listen for to know when a browser is sending Phaser into hibernation, and without RAF we've got no final game loop in order to do anything like stop audio. They ought to provide one, to be honest, but to my knowledge, as of now, they don't.
