### ISSUE TITLE
Adding a polygon to Matter physics changes its position

### ISSUE THREAD

**Issue by BMorearty** [phaserjs/phaser#6178]
## Version

* Phaser Version: 3.55.2

* Operating system: MacOS

* Browser: reproduces on Firefox, Chrome, Safari

## Description

Steps to reproduce:

1. Add a polygon gameObject to a Scene. 
2. Then add the same polygon to Matter using the `fromVerts` type.

BEHAVIOR: adding it to Matter shifts its position.

EXPECTED BEHAVIOR: the position is not affected by Matter.

## Example Test Code

https://codepen.io/bmorearty/pen/RwMLrpd?editors=0011

## Additional Information

Rectangles and circles don't have this problem. Only polygons. As shown in the code sample.

I don't know if this is a bug in Matter or in the integration between Matter and Phaser. I suspect it's in the integration because Phaser has to determine the location of the gameObject before passing it to Matter.

**Comment by photonstorm** [comment]
Matter objects are positioned based on their centre of mass. For a circle or rectangle this is a fixed point. For a polygon it depends entirely on the vertices and if those have been centred around the CoM, or not. In this case, they haven't been.

**Comment by BMorearty** [comment]
I see, thank you. 

For an arbitrary polygon that may not be centered around the CoM, is there a way to keep it positioned it at the intended location?

Or to put it another way: would you consider this a bug in the Phaser integration with Matter? It still kind of seems that way to me, since I wouldn't expect an object to move due to being added as a static physics object.

**Comment by photonstorm** [comment]
It's important to understand that a Polygon Game Object and a Matter Body are two very different things, they work entirely differently internally and do not share common or compatible data. For a Polygon Game Object, we can draw the points as you define them because they are only needed for rendering and not for physics. We can simply render lines between them and fill that space in. Nice and easy.

But for Matter, the polygons that comprise a Body must form a concave hull (and be given in clockwise order). They are decomposed into a set of separate shapes to achieve this if they are not. This means the points fed into a Matter Body don't always (in fact rarely) constitute the actual vertices the Body uses after creation.

However, Matter provides a function to translate the Vertices and another function to adjust the center of mass. `Body.setCentre()` would be the first function to look at - just make sure you don't set it to be a point outside of the convex hull, or it'll fail.

If the vertices are centered around the mass, then a Polygon Game Object will align correctly, such as with these shapes: https://labs.phaser.io/view.html?src=src/game%20objects/shapes/polygon%20with%20matter%20physics.js

An alternative may be to create the Matter Body first, then read the vertices from it and use those to create the Polygon Game Object, as they will already be adjusted.

**Comment by BMorearty** [comment]
I've updated the code sample with a more extreme case that I discovered: https://codepen.io/bmorearty/pen/RwMLrpd

Now, in addition to the polygon shifting by a few pixels when added to Matter, the Matter physics polygon is in a shifted very far away from where the polygon is rendered (and clearly not at the Center of Mass of the polygon). This causes the collisions to occur in the wrong place.

**Comment by BMorearty** [comment]
Thank you, I was writing my last comment before I read yours.

That's helpful information. I will experiment it some more.

**Comment by BMorearty** [comment]
Hello,

You were so kind to give me such a detailed answer and I didn't want to waste your time so I've spent the last day trying to figure this out on my own. I discovered what I think is another issue more troublesome than the original. The progress I've made is:

1. Realizing that if the upper left corner of a polygon's bounding box isn't 0,0 then the Matter body is placed in a different position than the rendered polygon. For example if the bounding box's top-left corner is -50,-50 then the polygon renders above and to the left of the origin by 50 pixels--but the Matter body is not offset. As a result, the collision detection and the rendering are not anywhere near the same place. I can't find anything in the Phaser documentation stating that the top left corner of a polygon's bounding box should be 0,0 so I'm not sure if this is a bug, an undocumented limitation, or a documented limitation whose docs I just haven't found.
2. Discovering that a similar behavior was happening for circles in Phaser 3.18.1 and was fixed in 3.19.0. I think [this was the fix](https://github.com/photonstorm/phaser/issues/4620). You can see the old circle bug in my codepen by going into Codepen Settings and changing the Phaser version to 3.18.1.

In this image, two polygons were added at the same origin and vertices as each other, with a top-left bounding box of -50,-50. The solid green polygon was not added to Matter; the solid magenta polygon was added to Matter and that caused it to render in a different place than the green one; and the magenta outline is where Matter placed the polygon's body for collision detection:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/16927/181378120-160765ae-ef36-4664-a213-9be41f45c105.png">

Here's a codepen to illustrate all of this: https://codepen.io/bmorearty/pen/XWEepLp

Here's an illustration of similar behavior for a circle from Phaser 3.18.1:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/16927/181378707-d30c21c6-5c61-424c-aed4-2f8be57c0b70.png">

**Comment by photonstorm** [comment]
The Circle issue from 3.18 is unrelated entirely, it's nothing to do with physics. It was just the fact it used the radius value instead of the diameter for the position.

From the Polygon documentation: "By default the `x` and `y` coordinates of this Shape refer to the center of it. However, depending on the coordinates of the points provided, the final shape may be rendered offset from its origin."

Which is precisely what is happening here. You have given it points that are not based on 0x0 being the center, so it will render offset from that and the body.

As I said last time - the vertices a polygon uses and those a Matter Body uses are largely incompatible and will need manipulating to be used together. Here are two such ways, one for 0x0 based points and one for offset points:

```js
class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    create ()
    {
        this.matter.world.setBounds(0, 0, 800, 600);
        this.matter.add.mouseSpring({ stiffness: 0.1 });

        const verts = [
          { x: 50, y: 0 },
          { x: 100, y: 60 },
          { x: 0, y: 75 }
        ];

        //  This will work properly because the vertices are
        //  centered around 0x0

        const body = this.matter.add.fromVertices(300, 300, verts);

        const poly = this.add.polygon(body.position.x, body.position.y, verts, 0x8d8d8d);

        //  Tell the Game Object to use the existing body, don't create a new one
        this.matter.add.gameObject(poly, body, false);

        //  In this case the verts are not centered, so we cannot
        //  use them to create the Polygon from. Instead we create
        //  the body first and use _those_ verts to create the Polygon

        const verts2 = [
            { x: 0, y: -50 },
            { x: 50, y: 10 },
            { x: -50, y: 25 }
        ];

        const body2 = this.matter.add.fromVertices(500, 300, verts2);

        const polyVerts = [];

        const bx = body2.position.x;
        const by = body2.position.y;

        const cx = body2.centerOffset.x;
        const cy = body2.centerOffset.y;

        body2.vertices.forEach(vert => {
            polyVerts.push({ x: vert.x - bx + cx, y: vert.y - by + cy });
        });

        const poly2 = this.add.polygon(bx, by, polyVerts, 0x8d8d8d);

        //  Account for the fact that in this set of verts, the
        //  origin isn't the center
        poly2.setDisplayOrigin(cx, cy);

        this.matter.add.gameObject(poly2, body2, false);
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: Example,
    physics: {
        default: 'matter',
        matter: {
            gravity: { y: 0 },
            debug: {

                showAngleIndicator: true,
                angleColor: 0xe81153,

                showVelocity: true,
                velocityColor: 0x00aeef,

                showCollisions: true,
                collisionColor: 0xf5950c,

                showBody: true,
                showInternalEdges: true,

                showPositions: true,
                positionSize: 4,
                positionColor: 0xe042da,

                showJoint: true,
                jointColor: 0xe0e042,
                jointLineOpacity: 1,
                jointLineThickness: 2,

                pinSize: 4,
                pinColor: 0x42e0e0,

                springColor: 0xe042e0,

                anchorColor: 0xefefef,
                anchorSize: 4,

                showConvexHulls: true,
                hullColor: 0xd703d0
            }
        }
    }
};

const game = new Phaser.Game(config);
```

Use mouse to drag the bodies around.

**Comment by BMorearty** [comment]
Thank you! This code sample helped me understand it.

I'm closing this because it sounds like there isn't a bug and I know how to get the behavior I want. But I'm still confused about how the following coordinates are "centered around 0x0". To me they clearly look like the top left of the polygon's bounding box is at 0x0, not its center:

```js
        const verts = [
          { x: 50, y: 0 },
          { x: 100, y: 60 },
          { x: 0, y: 75 }
        ];
```

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/matter-physics-polygon-body-has-weird-offset/14762/2
