### ISSUE TITLE
Typeerror when passing custom class in CreateFromObjectLayerConfig

### ISSUE THREAD

**Issue by kpotschi** [phaserjs/phaser#6318]
## Version
* Phaser Version:
* 3.60.0-beta.17

## Description

Getting a type error when defining an alternative GameObject Type in Phaser.Tilemaps.Tilemap.createFromObjects()

`
Type 'typeof Image' is not assignable to type 'CreateFromObjectsClassTypeConstructor'.
`

## Example Test Code

```
map.createFromObjects('background', [
		{ gid: 1, key: 'background1', classType: Phaser.GameObjects.Image },
		{ gid: 2, key: 'background2', classType: Phaser.GameObjects.Image },
	])
```

**Comment by bilalnawaz072** [comment]
If you are getting a TypeError when passing a custom class in the createFromObjectLayer method in Phaser 3, it could be because the class is not being properly mapped to the type in the ObjectLayerConfig object.

The createFromObjectLayer method expects the ObjectLayerConfig object to contain a type property that maps to the class you want to create. For example:

```
const config: ObjectLayerConfig = {
  type: MyCustomClass,
  ...
};

createFromObjectLayer(config);
```


If the type property is not correctly mapped to the custom class, you will get a TypeError when trying to create an instance of the class.

To fix this issue, make sure that the type property in the ObjectLayerConfig object is correctly set to the custom class. Here is an example of how you can do this:


```
class MyCustomClass extends Phaser.GameObjects.Sprite {
  // Class implementation
}

const config: ObjectLayerConfig = {
  type: MyCustomClass,
  ...
};

createFromObjectLayer(config);

```

**Comment by samme** [comment]
I guess this is a TypeScript limitation and these need to be changed back to `Function`. 😞 

- `CreateFromObjectsClassTypeConstructor`
- `GroupClassTypeConstructor`
- `ParticleClassConstructor`

 
![CreateFromObjectsClassTypeConstructor](https://user-images.githubusercontent.com/435681/208161264-3d3f37a0-3687-42d5-9893-f90d57c78222.png)

**Comment by photonstorm** [comment]
@samme  Yeah I think that might make sense.

Also, bit fed up with the OpenGPT spam issue comments I'm seeing here now.
