### ISSUE TITLE
Meshes in 3.55.2

### ISSUE THREAD

**Issue by MadDogMayCry0** [phaserjs/phaser#6343]
I tryed to use dragonbones on last 3.55.2 release, and it's seems to be was changed. I dont sure what, but pls, take a look on this post 
https://phaser.discourse.group/t/dragonbones-improvments/7673/29?u=maddogmaycry
(to not duplicate this). Is this any some new feature i miss? Sry, i not observe last changes in Phaser long time. :(

In 3.5.0Beta9 in dragonbones plugin it's works like

```javascript
//Create mesh
DragonBonesScenePlugin.prototype.createMeshDisplayPlaceholder = function () {
   return new phaser.display.SlotMesh(this.scene, 0, 0, [], [], [], [], [], null, null);
};
//add to container
Slot.prototype._addDisplay = function () {
   this.armature.display.add(this._renderDisplay);
 };
```
![Безымянный](https://user-images.githubusercontent.com/2493591/212269730-6e8f9c28-098e-497b-b2bc-b76b1e774c46.png)

And content of pipline is different.
Do i need change something?

**Comment by photonstorm** [comment]
Are you sure the DragonBones plugin was updated to work with Phaser 3.55? I assume not, based on the forum thread and the error you're getting.

Doesn't DragonBones provide its own WebGL runtime? (like Spine does), in which case, it would be much easier to just use the Phaser Extern Game Object, hand over processing to DragonBones to let it do all the rendering, then carry on again afterward. This is how Spine works.

Eitherway, there's not much I can do with this issue as it stands. I'd need a fully running test please, with the asset files, in order to see if this is just an issue with the Mesh Game Object, or an issue with the plugin itself.

**Comment by MadDogMayCry0** [comment]
> Are you sure the DragonBones plugin was updated to work with Phaser 3.55? 

I tryed to fix some bugs to my self a long time ago, and 2 days ago i did meshes just for fun. But it's not works on 3.55.2 :( i attach a files in your community thread, u can download it from last topic.

> Doesn't DragonBones provide its own WebGL runtime? 

No, He's just an intermediary who manipulates the phaser's game object.

> Eitherway, there's not much I can do with this issue as it stands. I'd need a fully running test please, with the asset files, in order to see if this is just an issue with the Mesh Game Object, or an issue with the plugin itself.

@photonstorm Pls take a look on last topic from link above! It's all files over there.
https://phaser.discourse.group/t/dragonbones-improvments/7673/30?u=maddogmaycry

**Comment by MadDogMayCry0** [comment]
@photonstorm no news?
