### ISSUE TITLE
"_" character displays as a space in Phaser.GameObjects.Text objects

### ISSUE THREAD

**Issue by swanny0819** [phaserjs/phaser#6356]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows 11
* Browser: reproduced in firefox, chrome, and edge

## Description

When creating text in a scene via .add.text, if the text contains a "\_" character, the "\_" character will be displayed as a space. The actual value of the text still contains the underscore - this is only a display problem.

## Example Test Code

class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    create ()
    {
        let testText = this.add.text(400, 32, "Click_to_create_animations", { color: '#00ff00' })
            .setOrigin(0.5, 0);
            console.log(testText.text);
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [ Example ]
};

const game = new Phaser.Game(config);

**Comment by samme** [comment]
Change to `"Click_\nto_\ncreate_animations"` and what appears?

**Comment by swanny0819** [comment]
If you do that, it displays two of the underscores, but not the third, like so:

Click_
to_
create animations

**Comment by swanny0819** [comment]
I see that putting a line break in there causes all preceding, but not following, underscores to be displayed. So
"Click_to_create_\nanimations" becomes

Click_to_create_
animations

but "Click_to_\ncreate_animations" becomes

Click_to_
create animations

**Comment by samme** [comment]
Probably the line height is too small and that character is getting cut off.

You can add

    testString: '|MÃ‰qgy_'

or

    padding: { y: 1 }

to the text style.

**Comment by photonstorm** [comment]
I bet it doesn't get factored into the text metrics. Add line padding and it'll display. Probably font specific too.

**Comment by samme** [comment]
Could add `_` to Phaser's test string.

**Comment by swanny0819** [comment]
Adding |MÃ‰qgy to the string does not cause the _ to display.
padding: { y: 1 } does cause it to display.

It does appear to be font-specific: the problem doesn't occur when I switch from the default font family to Arial.

**Comment by samme** [comment]
The `testString` has to include `_`, e.g. `|MÃ‰qgy_`.

**Comment by swanny0819** [comment]
Whoops. That's a mistake in my comment, not the code I tested. 

Adding |MÃ‰qgy_ to the string doesn't cause the _ to display.

**Comment by SlimHajRomdhane** [comment]
This issue is related to the font used by the Phaser.GameObjects.Text object. Some fonts may not render the "_" character correctly when it is used in a Text object.

One workaround is to add line padding to the text style, as suggested by the contributors in the issue discussion. This will cause the Text object to have a taller height, which can prevent the "_" character from getting cut off.

Another workaround is to use a different font that renders the "_" character correctly. You can do this by loading a custom font and setting it as the font family for the Text object. For example:

this.load.bitmapFont('myFont', 'assets/my-font.png', 'assets/my-font.xml');
let testText = this.add.bitmapText(400, 32, 'myFont', 'Click_to_create_animations', 32)
    .setOrigin(0.5, 0);

In this example, we are loading a bitmap font using this.load.bitmapFont and setting it as the font family for the Text object by passing the font name ('myFont') as the third argument to this.add.bitmapText.

I hope this helps! 
- SlimHR

**Comment by photonstorm** [comment]
If adding the underscore to the test string doesn't work, then I suspect it simply doesn't get calculated correctly in the Canvas API `measureText` call, which is what we use internally to get the line height from. Not sure there is much we can do about it I'm afraid, we have to rely on the values we get (`actualBoundingBoxAscent` and `Descent`). At least you have a solution by way of the `padding` property.
