### ISSUE TITLE
setScale on matter bodies is resetting fixedRotation

### ISSUE THREAD

**Issue by sushovande** [phaserjs/phaser#6369]
calling `Phaser.Physics.Matter.Sprite.setScale(...)` also resets the rotational inertia

## Version

* Phaser Version: Phaser v3.60.0-beta.18

* Operating system: Windows 10

* Browser: N/A, tested on chrome and firefox

## Description

calling `Phaser.Physics.Matter.Sprite.setScale(...)` also resets the rotational inertia
When setting up matter bodies, we have to first set scale and then call setFixedRotation, otherwise setFixedRotation has no effect

## Example Test Code

To demonstrate, open this example: https://labs.phaser.io/edit.html?src=src/physics/matterjs/fixed%20rotation.js
and add this to line 34: `block.setFixedRotation(); block.setScale(0.7);` Notice how the box rotates
if you instead switch the sequence  `block.setScale(0.7); block.setFixedRotation();` Notice how the box does not rotate as expected

**Comment by SlimHajRomdhane** [comment]
A workaround for this issue could be to set the rotational inertia after setting the scale.

Example code:

block.setScale(0.7);
block.setInertia(block.body.mass * block.width * block.width);
block.setFixedRotation();

This sets the scale first, then manually calculates the new rotational inertia based on the updated dimensions of the body, and finally sets the fixed rotation. This should give the expected behavior without resetting the rotational inertia.

I hope this helps!
- SlimHR

**Comment by likeavenus** [comment]
+++

**Comment by mohsen159** [comment]
+++

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
