### ISSUE TITLE
zoomFactor property of game object

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6374]
Set `scrollFactorX`, `scrollFactorY` properties of game object to `0` could ignore camera scrolling for ui game objects.
However, these properties could not ignore camera zooming, adding `zoomFactor` for camera.zoom might be a straightforward solution. 

( Workaround solution #6372 , adding 2nd camera for a specific layer )

**Comment by photonstorm** [comment]
This would be a massive change internally. Here's a small part of the `batchSprite` method in the Multi Pipeline:

```js
        spriteMatrix.applyITRS(gx, gy, gameObject.rotation, gameObject.scaleX * flipX, gameObject.scaleY * flipY);

        camMatrix.copyFrom(camera.matrix);

        if (parentTransformMatrix)
        {
            //  Multiply the camera by the parent matrix
            camMatrix.multiplyWithOffset(parentTransformMatrix, -camera.scrollX * gameObject.scrollFactorX, -camera.scrollY * gameObject.scrollFactorY);

            //  Undo the camera scroll
            spriteMatrix.e = gx;
            spriteMatrix.f = gy;
        }
        else
        {
            spriteMatrix.e -= camera.scrollX * gameObject.scrollFactorX;
            spriteMatrix.f -= camera.scrollY * gameObject.scrollFactorY;
        }

        //  Multiply by the Sprite matrix, store result in calcMatrix
        camMatrix.multiply(spriteMatrix, calcMatrix);
```

In here we'd need to add in conditional checks to see if the camera is zoomed + if the sprite is ignoring it, then undo that calculation from the matrix multiplication. This is just one place that check would need to be added (there are lots, lots more), and it would performance impact every single Sprite being rendered.

If it was trivial to add, I would do it, but there are so many things it would touch, all just because someone finds it a bit tricky to create a 2nd Scene? I'm not sure the trade-off is worth it to be honest. I think it can be more easily solved with education / examples.

**Comment by rexrainbow** [comment]
Thanks for explaining. You are right, `zoomFactor` for `zoom` is not similar with `scrollFactorX` for `scrollX`.
A dedicate camera in 2nd camera (or 2nd scene) would be better, especially combine layer with camera.
