### ISSUE TITLE
Aseprite animations do not play when frames have variable durations

### ISSUE THREAD

**Issue by tobx** [phaserjs/phaser#6410]
Loading Aseprite animations (`png`and `json`) with `scene.load.aseprite` and `scene.anims.createFromAseprite` does work and the frame duration is respected, but only when all frames have the same duration. Otherwise the animation is not played at all and just waits at the first frame.

I am using phaser 3.55.2.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG-v3.60.md).

**Comment by tobx** [comment]
Oh, that is great. I will have a look into closed issues and change log before posting next time, sorry.
