### ISSUE TITLE
Camera (?) post FX issue

### ISSUE THREAD

**Issue by darrylthom** [phaserjs/phaser#6427]
## Version

* Phaser Version: Beta 21, although this started in the version that added post effects.

* Operating system: Windows

* Browser: Chrome

## Description
With my game, I have it fill the entire screen. Upon resizing the window, if the screen is large then I set the width to 1088 and height to 512 and scale to fit. With camera post effects, it seems to ignore the width and height I set the game size to.

## Example Test Code
Very rough example I will update later if you can't figure out the root issue

this.camera.postFX.addBarrel(0.9);

Upon resizing window and it is considered a large size:

this.game.scale.autoCenter = Phaser.Scale.CENTER_BOTH;
this.game.scale.scaleMode = Phaser.Scale.FIT;
this.game.scale.setGameSize(1088, 512);
this.game.scale.refresh();

This seems to happen when an effect is on the camera.
<img width="309" alt="Camera-PostFX-Bug" src="https://user-images.githubusercontent.com/51373789/227654471-77c04dad-3027-4bc0-9a12-c02f06c7d227.png">

## Additional Information
I am assuming there is some sort of width or height component to the effects being applied.

**Comment by SlimHajRomdhane** [comment]
It's possible that the post effect shader is using the default canvas size instead of the game size you set. You can try setting the inputSize uniform in the shader to the size of your game to ensure it uses the correct size. You can do this by adding the following code in your scene's create() method:

this.camera.postFX.setFloat2('inputSize', this.scale.width, this.scale.height);

This will set the inputSize uniform in the post effect shader to the width and height of your game. Replace this.scale.width and this.scale.height with the actual width and height values you set for your game.

I hope this helps!
- SlimHR

**Comment by photonstorm** [comment]
This is the same issue as in #6503 - so I'm going to close this one to keep it tidy and refer to that one with the fix.
