### ISSUE TITLE
Phaser.GameObjects.GameObjectCreator adds objects to displayList by default

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6446]
## Version

* Phaser Version: from 3.55.2, 3.60b19, 3.60b22 (likely others)

## Description

`Phaser.GameObjects.GameObjectCreator` adds display objects to displayList (Scene or Container). This should not happenn, eg docs specifically state that using `make` should not add objects to DL: 
https://newdocs.phaser.io/docs/3.60.0-beta.22/Phaser.GameObjects.GameObjectCreator

## Example Test Code
```ts
this.make.image({key:'myTextureKey'});
```

## Additional Information
@Kal_Torak (discord) was able to find the specific code where this happens ('add' set to 'true'):
https://discord.com/channels/244245946873937922/416623653741133837/1092332470294282270

Instead, add should be set to false by default.

**Comment by photonstorm** [comment]
This behavior is correct - the `addToScene` parameter was added in version 3.7.1 (8th May 2018) as a convenience to allow you not always to have to set `add: false` in the config itself (first parameter). Before this point, you had to put it in the config, and I was getting fed up doing it all the time, so added the parameter to make life a bit quicker.

If you _do_ set this value in the config, then it'll use that setting. Otherwise, if you do specify the 2nd parameter, it will use that to override the config. Finally, if you don't do any of those, it defaults to 'true' (and has done since the beginning).

I may clarify this better in the docs, but I'm not switching the default value 5 years later 🙂

**Comment by samme** [comment]
I think people are confused by

> Unlike the Game Object Factory, they are not automatically added to the Scene.

What happens is

- They are added to the scene update list.
- They are added to the scene display list unless you pass `add: false` or `addToScene = false`.

**Comment by photonstorm** [comment]
Sure,  although I bet the number of people who read the docs for that class is likely just those of us here :) Either way, I can't change this, as it has worked this way forever. I'll just remove that comment from the docs.
