### ISSUE TITLE
Phaser.Tilemaps.Tilemap.putTileAt() failing

### ISSUE THREAD

**Issue by kpotschi** [phaserjs/phaser#6497]
## Version

* Phaser Version: 3.60.0
* Operating system: MacOS

## Description

The method is failing with
`Uncaught TypeError: can't access property "tileWidth", set is undefined`

originating from
`@function Phaser.Tilemaps.Components.PutTileAt`

In the documentation, as well as the types, the method expects `string | number | [Phaser.Tilemaps.TilemapLayer]`, while in the static method this is based off, `Phaser.Tilemaps.LayerData` is expected to be passed in. 

Tracing the error, you can see that `var set = layer.tilemapLayer.tileset[sid];` is trying to be accessed, which does not exist if `typeof layer === Phaser.Tilemaps.TilemapLayer`.

Using `@ts-ignore` and passing in Phaser.Tilemaps.TilemapLayer.layer, makes everything run without errors, but fails to essentially put the new tile in it's place.

## Example Test Code

```
const map = scene.make.tilemap({ key: 'test-map' })

const beachTileset = map.addTilesetImage('beach', 'tileset_beach')

const groundLayer = map.createLayer('ground', beachTileset, 0, 0)

// @ts-ignore
map.putTileAt(67, 1, 1, true, groundLayer.layer)

groundLayer.setCollisionByProperty({ collides: true })

scene.matter.world.convertTilemapLayer(groundLayer)
```

**Comment by photonstorm** [comment]
Have tested this and it works fine. Here's the test code (you can get the assets from our examples repo):

```js
class Example extends Phaser.Scene
{
    preload ()
    {
        this.load.image('tiles', 'assets/tilemaps/tiles/platformer_tiles.png');
    }

    create ()
    {
        const map = this.make.tilemap({ tileWidth: 16, tileHeight: 16, width: 25, height: 20 });

        const tiles = map.addTilesetImage('tiles');

        const layer = map.createBlankLayer('layer1', tiles);

        map.putTileAt(77, 1, 1);
        map.putTileAt(77, 2, 1, true, layer);
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#00000',
    parent: 'phaser-example',
    pixelArt: true,
    scene: Example
};

const game = new Phaser.Game(config);
```

and here's a screenshot:

![image](https://github.com/phaserjs/phaser/assets/164476/a24d4414-bb0a-4e75-a091-cb29ebc1500f)

The first tile uses the standard `putTileAt` and the second uses the layer as the parameter.

The `putTileAt` method does take a `TilemapLayer`, not a `LayerData` - because the layer data is looked-up as part of the call to `getLayer`:

```js
    putTileAt: function (tile, tileX, tileY, recalculateFaces, layer)
    {
        if (recalculateFaces === undefined) { recalculateFaces = true; }

        layer = this.getLayer(layer);

        if (layer === null) { return null; }

        return TilemapComponents.PutTileAt(tile, tileX, tileY, recalculateFaces, layer);
    },
```

Here you can see `layer = this.getLayer(layer)` will return the LayerData from the instance given. So yes, the static function does need a LayerData, but that is what gets passed to it.
