### ISSUE TITLE
Vercel deploy failed

### ISSUE THREAD

**Issue by callmejm** [phaserjs/phaser#6507]
I using vite, and use vercel to import from git
![image](https://user-images.githubusercontent.com/6957533/236990516-4305e448-8d11-4f48-b5f9-266448e4def3.png)

`ts.config.json`

```
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["DOM", "DOM.Iterable", "ESNext","es6", "dom", "dom.iterable", "scripthost"],
    "typeRoots": ["./node_modules/phaser/types"],
    "types": ["Phaser"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}

```

**Comment by photonstorm** [comment]
Sorry, but we're not going to look at this from our end. There are just too many different bundlers and deployment services out there for us to test them all. We've seen lots of devs using Phaser with Vite, so the issue is clearly on the Vercel integration somewhere.

Hopefully, someone else may know, but we don't have the time to investigate this directly.
