### ISSUE TITLE
Text Format Broken in Intel(R) Iris(R) Xe Graphics

### ISSUE THREAD

**Issue by JaspreetSinghSahni-OUP** [phaserjs/phaser#6522]
## Version

* Phaser Version: 3.60.0

* Operating system: Windows 10

* Browser: Chrome 112

## Description

When text is getting loaded on the Chrome 112 version windows 10 machine, text is broken, Graphis driver used is Intel(R) Iris(R) Xe Graphics. and the same this is working in Other machine which has different Graphics Driver Installed  Intel(R) UHD Graphics 620.

As You can see the Below text 39 and 25 are not render clearly, text is broken

## Example Test Code

Phaser Configuration

static config = {
    type: Phaser.CANVAS,
    scale: {
      mode: Phaser.Scale.FIT,
      autoCenter: Phaser.Scale.CENTER_BOTH,
      parent: "game",
      width: 1920,
      height: 1080,
    },
    dom: { createContainer: true },
    physics: {
      default: "arcade",
      arcade: {
        // debug: true
      },
    },
    scene: [LandingPage, MainScene, SaveScore, ShowScore],
  };

## Additional Information

<img width="91" alt="image" src="https://github.com/photonstorm/phaser/assets/86958124/2bd184c4-a927-4e17-8565-e95777218ab6">

<img width="43" alt="image" src="https://github.com/photonstorm/phaser/assets/86958124/cebf973b-9687-47ef-81a5-15b5ba32649f">

**Comment by photonstorm** [comment]
Chrome v112 is not the most current build (at least not for 64-bit) - so what happens if you update it to v114 current?

Text is rendered via a hidden Canvas. We have no control over the GPU (you cannot even determine the GPU model from JavaScript due to privacy) - and this isn't using WebGL, as you're forcing it to use Canvas in the config, so I'm not sure the driver even matters terribly.

You don't show the code for the text itself, is this a DOM Game Object or a Text Game Object?

**Comment by photonstorm** [comment]
Sorry, but I'm going to close this issue. I don't believe it's anything we have any control over, as we literally use the Canvas API to draw text. This sounds like a hardware driver issue.
