### ISSUE TITLE
Add parallax properties to Tilemaps

### ISSUE THREAD

**Issue by tobx** [phaserjs/phaser#6524]
[Tiled](https://www.mapeditor.org/) supports parallax layers. If you set the map properties `Parallax Origin` (`X` and `Y`) and the layer or object properties `Parallax Factor` (`X` and `Y`) and scroll through the map you can directly see the parallax effect. That comes in handy, because you do not need to export and import the map in phaser and load a level with it in order to test the parallax effect. The properties are stored as `parallaxx` and `parallaxy` in the exported tilemaps.

Afaik phaser does not parse those values and one does not have access to it. Currently I workaround that by adding redundant custom properties `scroll-factor-x` and `scroll-factor-y`.

It would be great, if phaser would parse those values directly.

**Comment by photonstorm** [comment]
Having read the Tiled docs on this, it sadly doesn't look as simple as just setting the scroll factor to be the parallax values, because of the complication of the parallax offset Tiled has - they even allude to this (i.e. you can't use it directly) in their docs: https://doc.mapeditor.org/en/stable/manual/layers/#parallax-reference-point - as it stands, I'd rather devs just adjust the scroll factor as needed themselves, rather than try to emulate it incorrectly by using the parallax values different to how Tiled uses them.
