### ISSUE TITLE
Audio is not spatial when playing in Firefox

### ISSUE THREAD

**Issue by starry-abyss** [phaserjs/phaser#6649]
* Phaser Version: 3.60
* Operating system: macOS Ventura 13.5.2
* Browser: Firefox 118.0.1

## Description

Audio is spatial in Chrome and Safari, but not in Firefox

## Example Test Code

Please run this demo, by clicking the lowest text (it's a button):
https://starry-abyss.github.io/find_the_black_cat/

When you move the mouse, all sounds all spatial relative to the mouse (but not in Firefox).

The source code is viewable in the browser.

## Additional Information

Firefox console says:
> An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.

But I think this shouldn't be the cause, as sound itself works, it's just not spatial

And also, the issue was discovered on Windows, so shouldn't be OS-specific.

**Comment by paxperscientiam** [comment]
~Is your example still working? I don't hear anything from that webpage in any browser.~

nvm, i found the button :)

**Comment by photonstorm** [comment]
We've taken the decision to recode the Phaser Audio system from scratch and replace the existing one. This will remove the division between Web Audio and HTML Audio (you'll be able to have both together), along with lots of other required features and API updates. Development work will start in Q2 2024. As a result, we are going to mothball all audio-related issues rather than try to monkey-patch solutions in.
