### ISSUE TITLE
DOM Object Visibility Incompatible with Nested Containers

### ISSUE THREAD

**Issue by Flashfyre** [phaserjs/phaser#6699]
## Version
* Phaser Version:
* v3.70.0 (WebGL | Web Audio)

* Operating system:
* Windows 10

## Description

Dom objects do not respect the visibility (and possibly other properties) of parents of parent containers when using nested containers.

## Example Test Code

https://codepen.io/rexrainbow/pen/ExMjKXo

## Additional Information

N/A

**Comment by rexrainbow** [comment]
[Here](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/domelement/DOMElementCSSRenderer.js#L39C1-L39C22) is the logic of visible checking. It tests if parent container is visible or not (`src.parentContainer.willRender()`).
In case of nested container, parent's parent container might be invisible, so that this parent container's `willRender()` ought to return `false`, imo.

**Comment by photonstorm** [comment]
This is correct. They will only respect the values of their immediate parent. I thought I had added this to the docs, but I see that I forgot - so it has now been included.
