### ISSUE TITLE
Phaser.GameObjects. TileSprite - WebGL (POT/NPOT)

### ISSUE THREAD

**Issue by Vladimirovich152** [phaserjs/phaser#6742]
An important note about Tile Sprites and NPOT textures: Internally, TileSprite textures use GL_REPEAT to provide seamless repeating of the textures. This, combined with the way in which the textures are handled in WebGL, means they need to be POT (power-of-two) sizes in order to wrap. If you provide a NPOT (non power-of-two) texture to a TileSprite it will generate a POT sized canvas and draw your texture to it, scaled up to the POT size. It's then scaled back down again during rendering to the original dimensions. While this works, in that it allows you to use any size texture for a Tile Sprite, it does mean that NPOT textures are going to appear anti-aliased when rendered, due to the interpolation that took place when it was resized into a POT texture. This is especially visible in pixel art graphics. If you notice it and it becomes an issue, the only way to avoid it is to ensure that you provide POT textures for Tile Sprites.

This needs to be fixed urgently! I and many others use pixel art, it's impossible to remove blurring in WebGL mode, and this is a colossal problem!

As a solution, you suggest using a texture size (for example, 512x512 or 1024x512), but even in that case, the blurring doesn't disappear. How can you stretch the image size without losing quality to fit the entire page?

I am using custom scaling:

`width: window.innerWidth * window.devicePixelRatio,
height: window.innerHeight * window.devicePixelRatio,
`

In this case, your solution will not work.

But I will also note that there is no blurring in CANVAS mode, but I cannot use CANVAS mode - it seems too slow.

Please do not suggest using CANVAS or a regular sprite as a solution.

---
A detailed description of the problem with screenshots is available in the Discord channel, but I was forced to write about it on GitHub. The issue is apparent, and it remains a mystery to me why it hasn't been fixed after so many years.

**Comment by photonstorm** [comment]
This feels like two entirely separate issues. Are all of your sprites TileSprites? I doubt it. Maybe just the background is? Are your TileSprite textures perfectly POT in size? If not, they will be scaled in order to create the underlying TileSprite texture. There's no way around this currently, and we document it clearly. And this scaling will nuke any pixel art, as we mentioned. If the texture is a POT size then it won't be blurred by WebGL as you can see in this example: https://labs.phaser.io/view.html?src=src%5Cgame%20objects%5Ctile%20sprite%5Ctilesprite%20pixel%20art%20test.js&v=dev - the pixel art is maintained at any _TileSprite scale_ (disable the rotation to make this clearer)

However, if the *game* canvas is scaled to a size or pixel ratio that isn't a perfect match for the art, then _all_ sprites will get scaled and become blurred, TileSprites included. And scaling the game to 'window innerWidth * DPI' is absolutely going to scale it to a size that isn't pixel-art friendly. because you're dealing with sub-pixel values. When that happens, interpolation is going to take place no matter what. To avoid it, the canvas needs to be scaled to a size that is a perfect even integer, not a fraction, and then to a perfect ratio scale for the art.

**Comment by Vladimirovich152** [comment]
Show me an example of using tileSprite as a background image along with

`this.game.scale.setGameSize(window.innerWidth * window.devicePixelRatio, window.innerHeight* window.devicePixelRatio);
`
and type: Phaser.WEBGL.

It seems impossible to achieve this.

**Comment by Vladimirovich152** [comment]
Okay, it works.
But there is an issue with setTexture for tileSprite. When changing the background, I have to delete the old object and create a new one.

**Comment by photonstorm** [comment]
I would need to see a code sample showing what you mean re: `setTexture` not working, because it does in our limited test. Would be useful to compare how you're doing it, with how we expect devs to do it. There should be no need to destroy the TIleSprite at all.
