### ISSUE TITLE
WebGL Texture Atlas are flipped when recovering from a context loss

### ISSUE THREAD

**Issue by yaustar** [phaserjs/phaser#6745]
## Version
* Phaser Version: 3.80.0
* Operating system: Mac

## Description

We create our own texture atlas at runtime using an offscreen canvas and create a blob url from the canvas to load into Phaser.

When we do a context loss and recovery test, the texture is flipped on the Y axis.

https://github.com/phaserjs/phaser/assets/16639049/24ab4733-14bc-4487-8443-bfdb4a46e1d7

## Example Test Code

WIP

Trying to create a repro test project but seems to be fine so far https://codepen.io/mikewong/pen/KKELRbK (wait one second for context loss)

Edit: I can provide a private staging build link of the project that has the issue if you contact me via `yaustar` on Discord

## Misc

Extra information about the texture if that helps
<img width="484" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/2ca44474-70d0-44aa-9dbe-61442e870a92">

**Comment by BenjaminDRichards** [comment]
Hi @yaustar ! This issue is difficult to pin down, as you've mentioned.

I assume that something in the Phaser code has set `gl.UNPACK_FLIP_Y_WEBGL` on the texture without changing the corresponding metadata that allows us to recover from context loss. But there are a lot of uses of `flipY` throughout the codebase, so it's proving difficult to isolate.

I _think_ it might be associated with a RenderTexture or a Shader game object. Are you using either of these with the texture? Can you try recreating the issue using any Shader game objects or RenderTexture game objects from your project? Also, if you are using dynamic textures, that could be relevant. Basically, whatever is touching the textures in your game could be responsible, so try recreating the steps that lead up to the texture inversion.

Alternatively, try _removing_ things from your game until the problem stops. Then try to recreate the issue using the last thing you removed.

If you can recreate the issue this way, that's great! It lets me debug more extensively at my end.

If it doesn't work, let me know and I'll be in touch about access to your private staging build. I try to avoid looking at private data, because not only is it private for a reason, it's often less useful than a really succinct recreation of the issue. (I'm in the New Zealand time zone and it's Friday, so I apologise if I don't get to it this week. But I do want to find out why this is happening.)

**Comment by yaustar** [comment]
We don't use RenderTextures or dynamic textures but we do use shaders for outlines on the objects. We barely touch the textures in our project beyond what I've tried to repro in the codepen https://codepen.io/mikewong/pen/KKELRbK

I will try disabling shaders in our project and see if that helps but beyond that, there isn't much more to remove 🤔 

Is there any specific information/data/class etc that I could look at when debugging to get more information about the texture to send over to you?

**Comment by yaustar** [comment]
Small update, we have two 'apps' that use Phaser and share some code between them. In the second app, the context recovery works as expected (no upside down textures) so I'm trying to track down differences

It also seems like it doesn't always flip all textures upside down. On rare cases, some of the textures are fine making me think there's a race condition somewhere

**Comment by BenjaminDRichards** [comment]
The best specific information is what you're giving us - the Codepen with a clear recreation of everything you're doing.

You could always put your actual blob texture into the Codepen, so we've got something as genuine as possible. The problem is, I can see it starts with `localhost` so it probably won't work on the web. The other stats you've shared for the texture look fine; it has non-power-of-two resolution, but so does the texture currently used in the Codepen.

Now, when you say "it doesn't always flip all textures upside-down', I want to clarify. I expect that the following are all true:

- All sprites taken from the blob texture are the same: flipped, or not flipped. You never have some flipped and some not flipped in the same session.
- Other sprites are never flipped.

Thanks for your input - I'll see if I can find anything on my own, but keep investigating!

**Comment by yaustar** [comment]
> Now, when you say "it doesn't always flip all textures upside-down', I want to clarify. I expect that the following are all true:
> 
> * All sprites taken from the blob texture are the same: flipped, or not flipped. You never have some flipped and some not flipped in the same session.
> * Other sprites are never flipped.

In our case, we have 4 main textures. 

* Background
* World objects (desks, chairs etc) (runtime packed atlas via our own system)
* World objects (atlas created at build time based on most common used objects)
* Avatars

During investigation, I've sometimes had one of the textures not flip on recovery. If it's the one of the world objects, all game objects using that atlas look correct.

It's not that sprites are flipped (as far as I can tell) but the texture itself so the sprites are showing a different part of the texture.

Some of the code in our project is legacy so I'm still investigating if there is anything we do to the texture when it is loaded but I can't see it doing anything more than what I'm doing in the code pen project.

The video shows localhost, but we can share a dev build on a server that can accessed by URL. It also has source maps so I can reference our config, scene etc code. 

I don't think the actual image used in our app will help as it works fine in the second app that I mentioned where recovered works fine.

The main difference between the two is that the one that has issues has a custom Game class that overrides step function so we can control the FPS we render at. Is there anything in the recovery or even load process in Phaser that we should be aware of that affects the texture properties?

**Comment by BenjaminDRichards** [comment]
> It's not that sprites are flipped (as far as I can tell) but the texture itself so the sprites are showing a different part of the texture.

Yes, that's clear from your video. The texture atlas data hasn't changed, but the image it's looking at has flipped upside-down, so we're seeing the wrong parts of the texture. It's good for you to confirm that, though, because I was assuming it was true.

> The main difference between the two is that the one that has issues has a custom Game class that overrides step function so we can control the FPS we render at. Is there anything in the recovery or even load process in Phaser that we should be aware of that affects the texture properties?

Here's what happens to a texture:

First, the texture data is loaded and stored. This is usually in an `Image`, but in this case, it's the blob data. This data shouldn't change after loading.

Second, the texture is sent to the GPU. Ideally, this goes through `WebGLRenderer.createTexture2D()`, which ensures that all the properties are stored in a `WebGLTextureWrapper`. The Wrapper then uses those properties to create the texture.

One of those properties is `flipY`, which instructs WebGL which end of the data is the top. This is called via `gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, this.flipY)`. This should _only_ be happening inside the wrapper.

Now the texture is set up and is ready to render. Nothing more should be changed on it.

Third, when the WebGL context is lost, the GPU forgets everything that was sent to it. WebGL's texture disappears completely.

Fourth, when the WebGL context is restored, we simply run the Wrapper's procedure again to create the texture. It should have the exact same settings as it did before, and recreate things exactly as they were.

However, if something has modified `UNPACK_FLIP_Y_WEBGL`, it will be lost with the lost context, and will not be recreated. And if something has modified `flipY` after the texture was created, it will not appear before the context is lost, but it _will_ appear _after_ the context is restored and the texture is recreated.

If your code is using those two keywords (`UNPACK_FLIP_Y_WEBGL` and `flipY`), it could be a sign that your code is doing something unexpected which interferes with the rendering. I don't think it is, because they're very specialised parts of the system that you'd have little reason to touch, but I should let you know.

More likely, something in Phaser is setting these values, and we've overlooked it. I know that a couple of other places in Phaser can modify `UNPACK_FLIP_Y_WEBGL`, particularly a render texture (a buffer which other systems can render to, and is then used as a texture for other render passes). `Shader` might run this if `setRenderToTexture()` is called - that's another keyword worth looking for.

Phaser might be setting something incorrectly in this process, but we haven't seen anything go wrong. So it's probably more subtle than that. I think you're correct about race conditions, or at least, things might execute in a different order. This might be due to the order in which textures finish loading, or it might be due to things moving around in your game world. But this data is usually handled only during scene creation, so it's probably happening when textures load in. Do you have any custom logic that happens when textures load in, or do you just wait for everything to be done?

I'll look at our code myself on Monday to see what's happening. Right now, I'm just laying out what I think are likely areas where something could be happening, partially as a reminder to myself - but maybe it'll reveal something in your code.

**Comment by yaustar** [comment]
> If your code is using those two keywords (UNPACK_FLIP_Y_WEBGL and flipY),

I couldn't find any calls/references to this in our code base

I'm still going down the shader route and disabling all the ones we use but haven't yet found a cause if there is one. Will recheck on Monday.

> Do you have any custom logic that happens when textures load in, or do you just wait for everything to be done?

At worse, we change the filtering between nearest and linear. AFAIK we don't process the textures any more than that.

**Comment by BenjaminDRichards** [comment]
> > If your code is using those two keywords (UNPACK_FLIP_Y_WEBGL and flipY),
> 
> I couldn't find any calls/references to this in our code base

That makes sense. I wouldn't expect them.

What about `setRenderToTexture`?

> I'm still going down the shader route and disabling all the ones we use but haven't yet found a cause if there is one. Will recheck on Monday.
> 
> > Do you have any custom logic that happens when textures load in, or do you just wait for everything to be done?
> 
> At worse, we change the filtering between nearest and linear. AFAIK we don't process the textures any more than that.

Just to clarify, _how_ do you change the filtering? There are a few ways to do that.

Also, do you want _everything_ in your game to be filtered to nearest, or to linear? If everything should be the same, I might have some pointers.

**Comment by yaustar** [comment]
> What about setRenderToTexture?

Not in our code base but I need to check if any shaders do this that we may have used

> Just to clarify, how do you change the filtering? There are a few ways to do that.

We access the textures from the textures manager and iterate through them calling `setFilter`

 > Also, do you want everything in your game to be filtered to nearest, or to linear?

We want them all to be one or the other based on the zoom level. That way we can retain detail on the pixel art when zoomed out and have the crisp pixels when the user zooms in.

In either case, I've removed the logic when testing for this issue and the issue is still there when this logic is disabled.

**Comment by BenjaminDRichards** [comment]
Alright, I've looked over Phaser and tidied up some code. It might help this issue.

To test this code, you just need to overwrite one of Phaser's functions with the new code. Make sure you're using Phaser 3.80.0. Add this code, BEFORE you make any calls to `Phaser`:

```js
Phaser.GameObjects.Shader.prototype.initSampler2D = function (uniform)
{
    if (!uniform.value)
    {
        return;
    }

    //  Extended texture data

    var data = uniform.textureData;

    if (data && !uniform.value.isRenderTexture)
    {
        var gl = this.gl;
        var wrapper = uniform.value;

        var magFilter = gl[(data.magFilter || 'linear').toUpperCase()];
        var minFilter = gl[(data.minFilter || 'linear').toUpperCase()];
        var wrapS = gl[(data.wrapS || 'repeat').toUpperCase()];
        var wrapT = gl[(data.wrapT || 'repeat').toUpperCase()];
        var flipY = (data.flipY || false);
        var width = (data.width || wrapper.width);
        var height = (data.height || wrapper.height);
        var source = (data.source || wrapper.pixels);

        if (data.repeat)
        {
            wrapS = gl.REPEAT;
            wrapT = gl.REPEAT;
        }

        if (data.width)
        {
            // If the uniform has resolution, use a blank texture.
            source = null;
        }

        wrapper.update(source, width, height, flipY, wrapS, wrapT, minFilter, magFilter);
    }

    this.renderer.setProgram(this.program);

    this._textureCount++;
};
```

Hopefully that fits into your code system.

I had to take some shortcuts to make this code work outside the Phaser build system. If it crashes your game, that's useful! Just add the following line to the start of the function: `console.log('initSampler2D uniform', uniform);`, and let me know how many times that runs and what it says each time. (Unless it runs dozens of times, in which case ⚠quickly close the tab and remove the line. It shouldn't do that, especially if it's crashing, but an unconstrainted console log can cause your computer to slow down.)

Let me know if that removes the flip issue. Even if it doesn't, that eliminates this area of code as a suspect.

**Comment by yaustar** [comment]
I had to create a custom build of Phaser with your patched code just to ensure that is was being used and the function is not called in the lifetime of the app (I've add a breakpoint and console logging to check)

`setRenderToTexture` is not called either using breakpoints to check

**Comment by BenjaminDRichards** [comment]
I didn't expect it to be so much work, sorry! Thank you for doing that.

So if none of this code is called, then the problem must be elsewhere. That's really weird, but I'll keep looking.

Just for the sake of inquiry, are there _any_ flipped textures in your game? You should be able to tell by running `game.renderer.glTextureWrappers.forEach(tex => {if (tex.flipY) console.log(tex);})` (or whatever fits in your game). A before/after context restore comparison might be informative. It would also be informative if you could compare results from a game session where it DOES flip to a game session where it DOES NOT flip. Note, this isn't checking the actual WebGL textures, just the cached data we use to recreate them. Checking the actual textures is a bit more challenging.

See also another issue: https://github.com/phaserjs/phaser/issues/6256, which also loads an external texture which is flipped upside-down. That one sounds like it always happens, so it's not exactly the same, but it does mention using `setUVs` to change the appearance of a texture. Does that ring any bells?

**Comment by BenjaminDRichards** [comment]
I've also made adjustments to `TextureSource.setFlipY`. This is a piece of code that's almost never called; Phaser only uses it to prepare Video-sourced textures for shaders to consume, and it shouldn't have any effect at all on textures which aren't sourced from a Canvas or Video. This will be in an upcoming release.

I don't _think_ it'll make a difference, but if you're using `TextureSource.setFlipY` anywhere in your code, it might be doing something.

Most uses of `setFlipY` are just on GameObjects, and shouldn't affect the texture system at all.

**Comment by yaustar** [comment]
> Just for the sake of inquiry, are there any flipped textures in your game? You should be able to tell by running game.renderer.glTextureWrappers.forEach(tex => {if (tex.flipY) console.log(tex);}) (or whatever fits in your game).

Okay, THIS is interesting. There is a texture that is flippedY but it isn't in `game.textures.list`. It's somewhere else that I need to track down.

<img width="794" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/a02a900f-a43d-4a34-8997-065664bdfd89">

In the other apps that share code libraries and don't have this issue, they don't have this extra texture so it's something unique to this particular app to track down.

If I comment out the code in WebGLTextureWrapper:

```
        if (this.flipY)
        {
            //gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
        }
```

Context recovery works fine.

I think this needs to be changed to so it's set on per texture upload basis as it's setting the current state of the gl context:
```
gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, this.flipY);
```

(What's annoying is that I did see that a texture was flipped before when I added a log point WebGLRenderer.js and didn't follow up on that thread 🤦  Thanks for your patience and troubleshooting)

**Comment by yaustar** [comment]
Some more findings:

I've done the following to debug in our app
<img width="698" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/0f671d26-f910-4a70-a368-dd0561a354d7">

When loading, the breakpoint in the if statement is not triggered yet running your log code shows the is one wrapper that has a Y flip (I will track that down later)

<img width="1115" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/50a86f0d-c873-4dbb-bdae-551ecdeb8fae">

When I go through the Loss/Recovery step, the breakpoint does trigger and we get the following output
<img width="483" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/e2468ad4-7bd4-4c97-ad04-00204f5b4ff7">

Where I've outlined is the first wrapper recovered to have a flipY set to true but any other textures recovered after it also have have the pixelStore set to flipY too.

Any new textures loaded after this point are also flippedY 😅

**Comment by yaustar** [comment]
> We don't use RenderTextures or dynamic textures but we do use shaders for outlines on the objects. We barely touch the textures in our project beyond what I've tried to repro in the codepen [codepen.io/mikewong/pen/KKELRbK](https://codepen.io/mikewong/pen/KKELRbK)

Oh fudge, I was wrong here 🤦 We DO use a render texture for an overlay effect that I forgot about so your suspicion is bang on the money. Sorry

Once I've disabled this, we no longer get upside down textures

**Comment by photonstorm** [comment]
The texture that is flipped is only 1x1 in size, so doesn't even need flipping!

**Comment by yaustar** [comment]
I was about to make a PR when I sync to latest and the issue is fixed as part of this commit you did a few days ago https://github.com/phaserjs/phaser/commit/9a5b51dd27a8255fa5e29d1482482cac02ad0090

<img width="1674" alt="image" src="https://github.com/phaserjs/phaser/assets/16639049/aad97120-bca9-4c98-a405-1737abb157b0">

> The texture that is flipped is only 1x1 in size, so doesn't even need flipping!

It gets resized at runtime to overlay where areas are private/not private :) It's also a RenderTexture so the flip is in Phaser

Closed as this is fixed on master.
