### ISSUE TITLE
TextureManager#getPixelAlpha throws exception with compressed textures 

### ISSUE THREAD

**Issue by yaustar** [phaserjs/phaser#6761]
## Version

* Phaser Version: 3.80.1

* Operating system: Mac

* Browser: Chrome

## Description

Calling `getPixelAlpha` on a compressed texture throws the following exception:

```
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
    at TextureManager.getPixelAlpha (3.80.1.js:215673:21)
    at Demo.create (eval at <anonymous> (frame.html:55:21), <anonymous>:25:35)
    at SceneManager.create (3.80.1.js:196456:26)
    at SceneManager.loadComplete (3.80.1.js:196363:14)
    at LoaderPlugin.emit (3.80.1.js:200:35)
    at LoaderPlugin.loadComplete (3.80.1.js:118769:14)
    at LoaderPlugin.fileProcessComplete (3.80.1.js:118735:18)
    at BinaryFile.onProcessComplete (3.80.1.js:117534:21)
    at BinaryFile.onProcess (3.80.1.js:121593:14)
    at LoaderPlugin.nextFile (3.80.1.js:118667:18)
```

## Example Test Code

Using this example: https://labs.phaser.io/edit.html?src=src\textures\compressed%20texture.js

Change the code to:
```
class Demo extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        this.load.texture('labs', {
            'ASTC': 'assets/compressed/labs-astc-4x4.pvr',
            'ETC1': 'assets/compressed/labs-etc1.pvr',
            'PVRTC': 'assets/compressed/labs-pvrtc-4bpp-rgba-srgb.pvr',
            'S3TC': 'assets/compressed/labs-bc3.pvr',
            'IMG': 'assets/compressed/labs.png'
        });
    }

    create ()
    {
        const logo = this.add.image(400, 300, 'labs');

        this.add.text(400, 570, logo.frame.source.compressionAlgorithm).setOrigin(0.5, 0);

        const foo = this.textures.getPixelAlpha(0, 0, 'labs');
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d6d',
    scene: Demo
};

const game = new Phaser.Game(config);
```

And see error in the console log of the browser.

## Additional Information

The full error stack in our project is from the InputPlugin when doing a hit test with pixelPerfect when setting interactive to true
```
test025:72 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
    at TextureManager.getPixelAlpha (phaser.js:215673:1)
    at Object.eval [as hitAreaCallback] (phaser.js:102191:1)
    at InputManager.pointWithinHitArea (phaser.js:103179:1)
    at InputManager.hitTest (phaser.js:103146:1)
    at InputPlugin.hitTestPointer (phaser.js:104250:1)
    at InputPlugin.update (phaser.js:104008:1)
    at InputManager.updateInputPlugins (phaser.js:102744:1)
    at InputManager.onMouseMove (phaser.js:102967:1)
    at HTMLCanvasElement.onMouseMove (phaser.js:116443:1)
    at HTMLCanvasElement.nrWrapper (test025:72:29516)
```

**Comment by photonstorm** [comment]
Yeah this isn't possible. We'll find a way to handle this more elegantly though!

**Comment by BenjaminDRichards** [comment]
I've added some checks to `getPixel` and `getPixelAlpha` to ensure they fail gracefully, rather than throwing exceptions.

The "impossibility" is because these methods work by drawing the texture to a 1x1 canvas, then pulling the canvas data and extracting the color channels. But a canvas can only accept data from sources compatible with the DOM: Image, Canvas, and Video. Other texture sources, such as compressed textures, render textures (using framebuffers under WebGL), etc will be rejected by the browser's Canvas API.

There are other ways to do this, but they're more complex and Phaser hasn't got them yet. A roundabout hack might be to use a `RenderTexture` and take a snapshot, which can pass the data back out to a DOM-compatible Image, although I haven't tested this.

For now, 0a2bede95e82a4e4966d71785beb8b86cfccf4f0 checks whether the texture source is DOM-compatible. That should give you enough to check validity yourself while we put together the next release.

**Comment by yaustar** [comment]
Awesome, thanks!
