### ISSUE TITLE
[4.0] Rectangle shape game object rendering

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6949]
## Version

* Phaser Version: 4.0 beta

* Operating system: window 11

* Browser: firefox

## Description

Create a rectangle shape : `this.add.rectangle(400, 300, 100, 100, 0x880000)`

[Test code](https://phaser.io/sandbox/tEowQm8v)
- Works fine on chrome desktop browser,
- Failed on firefox desktop browser,

Error message:

```
Error: Link Shader failed:Uniform `uResolution` is not linkable between attached shaders.
Line: 1 - Col 943156
```

**Comment by BenjaminDRichards** [comment]
Thanks for digging into 4.0!

The issue is that the `FLAT` shader used for rectangles and other shapes/graphics has a `vec2 uResolution` uniform in both the vertex shader and the fragment shader. However, the fragment shader will set it to `highp` precision if available, while the vertex shader will always use `mediump`. These are different types, so they cannot be in the same linked shader.

Firefox identifies this as a problem. Chrome does not, at least not on my machine. I don't know why. Perhaps mediump and highp are the same on my machine, and Chrome is OK with the error if it can compile it away. This is no guarantee that it would continue to work on all Chrome devices, though.

The fix is to add the same `highp` availability check to the vertex shader. This resolves the issue.

I also checked for other shaders that might have this problem, and I couldn't see any.
