### ISSUE TITLE
[4.0.0-beta.1] Firefox uncaught error on demo games: "Link Shader failed:Uniform `uResolution` is not linkable between attached shaders."

### ISSUE THREAD

**Issue by codingthat** [phaserjs/phaser#6951]
I first saw this with 4.0.0-beta.1 on my own game, but then noticed that also Create Phaser Game's "Memory Card Game" and "Coin Clicker" both exhibit this exact same behaviour.

They work normally on Chromium-based browsers, but not on Firefox (tested with both 131.0.3 and 132.0.1 on Linux Mint 20.3):

```
$ npm create @phaserjs/game@latest

...

✔ Enter Project Name: … my-phaser-game
✔ Select Option: › Demo Game (Matching Pairs, Clicker, Shmup)
✔ Select Demo Game: › Memory Card Game - Pair Matching Game

...

$ cd my-phaser-game/ &&  npm i phaser@4.0.0-beta.1 && npm run dev
```

Clicking the main graphic makes a sound, but doesn't start the game; the devtools console (even before clicking) shows this: [console-export-2024-11-16_20-18-39.txt](https://github.com/user-attachments/files/17787752/console-export-2024-11-16_20-18-39.txt)

**Comment by codingthat** [comment]
Same thing happens with "Coin Clicker."

**Comment by codingthat** [comment]
(And since this also happened with a game I'm developing locally, I thought this was maybe more about the beta than about https://github.com/phaserjs/create-game .)

**Comment by BenjaminDRichards** [comment]
Thanks for digging into 4.0.0!

The issue is that the `FLAT` shader used for rectangles and other shapes/graphics has a `vec2 uResolution` uniform in both the vertex shader and the fragment shader. However, the fragment shader will set it to `highp` precision if available, while the vertex shader will always use `mediump`. These are different types, so they cannot be in the same linked shader.

Firefox identifies this as a problem. Chrome does not, at least not on my machine. I don't know why. Perhaps mediump and highp are the same on my machine, and Chrome is OK with the error if it can compile it away. This is no guarantee that it would continue to work on all Chrome devices, though.

The fix is to add the same `highp` availability check to the vertex shader. This resolves the issue.

I also checked for other shaders that might have this problem, and I couldn't see any.
