### ISSUE TITLE
[v4] Resizing a RenderTexture errors

### ISSUE THREAD

**Issue by photonstorm** [phaserjs/phaser#6953]
```
this.add.renderTexture(400, 300, 100, 100).resize(200, 200), will rise these messages
```

Causes:

```
WebGL: INVALID_OPERATION: framebufferTexture2D: no framebuffer bound  WebGLFramebufferWrapper.js:243
WebGL: INVALID_OPERATION: framebufferRenderbuffer: no framebuffer bound WebGLFramebufferWrapper.js:265
```

**Comment by BenjaminDRichards** [comment]
This occurs when invoking `resize` in the same event as the RenderTexture is created.

It occurs because the framebuffer wrapper of the RT is bound upon creation, and remains bound when resize runs. Resize recreates the object inside the wrapper, but because the wrapper is already bound, it does not update the actual WebGL binding.

I've added a flag that forces the framebuffer object to be rebound. This solves the issue.
